{{- if .Values.serviceAccounts.dfclient.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dfclient.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dfclient.labels" . | nindent 4 }}
{{- end -}}