{{- if .Values.serviceAccounts.supernode.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "supernode.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supernode.labels" . | nindent 4 }}
{{- end -}}